on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.26.1
        with:
          github_token: ${{ github.token }}

      - name: Lint Protobuf files
        uses: bufbuild/buf-lint-action@v1.0.3
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}

  breaking:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1.26.1
        with:
          github_token: ${{ github.token }}

      - name: Check breaking changes
        uses: bufbuild/buf-breaking-action@v1.1.3
        with:
          against: 'https://github.com/Echin-h/grpc-template.git#branch=main'
          buf_token: ${{ secrets.BUF_TOKEN }}


  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - lint
      - breaking
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install Buf
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.11.0/buf-Linux-x86_64" -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Remove generated files
        run: rm -rf ./gen

      - name: Buf module update
        run: buf mod update

      - name: Buf generate
        run: buf generate

      - name: Run go mod tidy
        run: go mod tidy